Homework 1
Insomniacccc/2024-2-VK-EDU-Frontend-D-Alekhin pull request #1
Opened 2024-10-09 15:48 UTC by Insomniacccc

2024-10-10 04:59 UTC, martinkomitsky commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivanchello_br проверить его.
неправильный ник ментора

2024-10-10 05:02 UTC, Insomniacccc commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivanchello_br проверить его.
пофиксил

2024-10-11 15:07 UTC, martinkomitsky commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivanchello_br проверить его.
все равно неправильно, надо [Ivan-Bir](https://github.com/Ivan-Bir)

2024-10-11 15:08 UTC, martinkomitsky commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivanchello_br проверить его.
в заголовке поправил за тебя

2024-10-12 04:11 UTC, Insomniacccc commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivanchello_br проверить его.
Спасибо, не заметил что там знак другой

2024-10-12 16:20 UTC, Ivan-Bir requested changes
Критичных замечаний нет, но их надо поправить, потому что сроки упущены

2024-10-12 16:20 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +/*
Привет! Добро пожаловать на курс
Я буду твоим ментором и буду рад ответить на любые вопросы по курсу

2024-10-12 16:20 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +    let value = bytes / Math.pow(1024, index);
Значение не меняется, поэтому нужно использовать const

2024-10-12 16:20 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(0.5)).toBe('0.5 B');
Вот это как раз не очень логично с точки зрения информатики. Обычно все данные хранятся в целых байтах. Поэтому даже если на вход пришло дробное число, ответ должен вернуться в целых байтах

2024-10-12 16:20 UTC, Ivan-Bir commented on correctSentence.js
> +  let correctedText = text.charAt(0).toUpperCase() + text.slice(1);
Вместо конкатенации предпочтительнее использовать шаблонные строки 
\`${var}\`

2024-10-12 16:20 UTC, Ivan-Bir commented on correctSentence.test.js
> +  expect(correctSentence("Greetings, friends.")).toBe("Greetings, friends.")
Не хватает тестов на граничные случаи. Давай это исправим

2024-10-12 16:20 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  return data.filter(num => frequency.get(num) > 1);
Даже если у стрелочной функции один параметр, то его принято оборачивать в скобки

2024-10-12 16:20 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Тоже нет проверок граничных случаев

2024-10-16 17:37 UTC, Ivan-Bir requested changes, later dismissed
Не всё исправлено. Если не согласен с коментом, то пиши почему. Возвращаю на доработки

2024-10-16 17:37 UTC, Ivan-Bir commented on correctSentence.test.js
> +  expect(correctSentence(" ")).toBe(" .");
Выглядит больше, как невалидный ввод, поэтому обрабатывать нужно как и !text

2024-10-27 18:14 UTC, martinkomitsky commented
@Insomniacccc привет! получится довести до аппрува?

2024-11-10 10:50 UTC, martinkomitsky approved these changes
7

2024-11-10 10:50 UTC, merged